export { default as SendIcon } from './SendIcon'
export { default as MenuIcon } from './MenuIcon'
export { default as SwapTokenIcon } from './SwapTokenIcon'
export { default as TradeSwapIcon } from './TradeSwapIcon'
export { default as DisconnectIcon } from './DisconnectIcon'
export { default as MyProfileIcon } from './MyProfileIcon'